import { useState } from 'react'
import SourceDataFormat from '../components/SourceDataFormat'

const recipient = 'suryabonagiri69@gmail.com'
export default function SubmitData() {
  const [prepared, setPrepared] = useState(false)
  const [body, setBody] = useState('')
  const submit = (event) => {
    event.preventDefault()
    const data = new FormData(event.currentTarget)
    const text = `Restaurant Name: ${data.get('restaurant')}\nLocation: ${data.get('location')}\nInspection Date: ${data.get('date') || 'Not supplied'}\nSource URL: ${data.get('source') || 'Not supplied'}\nDetails: ${data.get('details')}\n\nSubmitted by: ${data.get('name') || 'Not supplied'}\nReply email: ${data.get('email') || 'Not supplied'}`
    setBody(text); setPrepared(true)
    window.location.href = `mailto:${recipient}?subject=${encodeURIComponent(`Restaurant information: ${data.get('restaurant')}`)}&body=${encodeURIComponent(text)}`
  }
  return <main className="page-shell py-12"><div className="mx-auto max-w-2xl"><p className="text-sm font-bold uppercase tracking-wider text-civic-700">Community contributions</p><h1 className="mt-2 text-3xl font-extrabold">Share restaurant info</h1><p className="mt-3 leading-7 text-slate-600">Share restaurant details or a public inspection source with the administrator. Your information will be reviewed before any record is added.</p><form onSubmit={submit} className="panel mt-7 space-y-5 p-6"><div className="grid gap-5 sm:grid-cols-2"><label className="label">Restaurant name *<input name="restaurant" className="field mt-1" required maxLength={120} /></label><label className="label">Locality / branch *<input name="location" className="field mt-1" required maxLength={150} /></label><label className="label">Inspection date, if known<input name="date" type="date" className="field mt-1" /></label><label className="label">Public source link<input name="source" type="url" className="field mt-1" placeholder="https://…" maxLength={500} /></label></div><label className="label">Details *<textarea name="details" className="field mt-1 min-h-40" required maxLength={2000} placeholder="Share the source text or describe the information you would like reviewed." /></label><div className="grid gap-5 sm:grid-cols-2"><label className="label">Your name (optional)<input name="name" className="field mt-1" maxLength={100} autoComplete="name" /></label><label className="label">Reply email (optional)<input name="email" type="email" className="field mt-1" maxLength={150} autoComplete="email" /></label></div><p className="text-sm leading-6 text-slate-600">This opens your email app with a draft addressed to <a className="text-civic-700 underline" href={`mailto:${recipient}`}>{recipient}</a>. Review the draft and press Send in your email app. Only include information you want to share with the administrator.</p><button className="button-primary">Prepare email</button></form>{prepared && <section className="panel mt-5 p-6"><p role="status" className="font-semibold">Email draft prepared — it has not been sent by this website.</p><p className="mt-2 text-sm text-slate-600">If your email app did not open, copy the details below into an email to {recipient}.</p><textarea aria-label="Prepared email text" readOnly value={body} className="field mt-4 min-h-52" onFocus={(event) => event.target.select()} /></section>}<SourceDataFormat /></div></main>
}
