import { CalendarDays } from 'lucide-react'
import StatusBadge from './StatusBadge'
import SourceLink from './SourceLink'
import InspectionEvidence from './InspectionEvidence'
const date = (value) => value ? new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${value}T00:00:00`)) : 'Not available in source data'
export default function InspectionTimeline({ inspections }) {
  if (!inspections.length) return <div className="panel p-6 text-slate-600">No historical inspections are available for this establishment.</div>
  return <ol className="relative ml-2 border-l-2 border-civic-100 pl-7">{[...inspections].sort((a, b) => (b.inspectionDate || '').localeCompare(a.inspectionDate || '')).map((item) => <li className="relative pb-8 last:pb-0" key={item.id}><span className="absolute -left-[37px] grid h-5 w-5 place-items-center rounded-full border-4 border-stone-50 bg-civic-600" /><div className="panel p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 font-bold text-slate-900"><CalendarDays size={17} className="text-civic-700" />{item.inspectionDate ? date(item.inspectionDate) : item.reportDate ? `Reported ${date(item.reportDate)} · Inspection date unknown` : date('')}</div><StatusBadge status={item.status} /></div><div className="mt-4 grid gap-4 sm:grid-cols-3"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Score</p><p className="mt-1 text-lg font-extrabold">{item.hygieneScore === null ? 'Not available' : `${item.hygieneScore}%`}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Key observations</p><p className="mt-1 text-sm leading-5">{item.observations?.join(', ') || 'Not available in source data'}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Action taken</p><p className="mt-1 text-sm leading-5">{item.actionTaken || 'Not available in source data'}</p></div></div><div className="mt-4"><SourceLink url={item.sourceUrl} handle={item.sourceHandle} originalPostUrl={item.originalPostUrl} /></div><InspectionEvidence inspection={item} /></div></li>)}</ol>
}
